### ISSUE TITLE
never reads date

### ISSUE THREAD

**Issue by MeY0u** [fu-hsi/FuGPS#10]
hello,
i ma using your lovely library and i receive data with it, but i cant receive date information. Is there any reason why?

**Comment by fu-hsi** [comment]
Hi.
It's simple.

`const char* time = fuGPS.getField(1);`

You have also available public fields:
```
byte Hours, Minutes, Seconds;
byte Days, Months, Years; 
```

Example:
`byte minutes = fuGPS.Minutes;`

**Comment by MeY0u** [comment]
so i do receive  the time but date no :( could it be that i receive so much
more GGA than RMC and it leaves RMC no chance?

**Comment by fu-hsi** [comment]
Sorry, but everything works on my side:

`stream.print(String(fuGPS.Years) + "." + String(fuGPS.Months) + "." + String(fuGPS.Days));`

Date is stored in RMC message.
Library needs at least one message of that type to parse date. Maybe your module is wrongly configured.

`fuGPS.sendCommand(FUGPS_PMTK_API_SET_NMEA_OUTPUT_RMCGGA);`

You can always check out demo programs to display detailed data or connect the module directly to the serial port and see what is being sent.

**Comment by MeY0u** [comment]
you are right that it should work, but it looks like the buffer is full of
GGA. can you guide me how can i add more satellites to read data? like
direction, giosepration, statliesinview.

**Comment by MeY0u** [comment]
```
#include <FuGPS.h>
#define NMEA_RX1 44  
#define NMEA_TX1 43

FuGPS fuGPS(Serial1);
bool gpsAlive = false;

void setup()
{
    Serial.begin(115200);
    Serial1.begin(38400, SERIAL_8N1, NMEA_RX1, NMEA_TX1);

    fuGPS.sendCommand(FUGPS_PMTK_SET_NMEA_BAUDRATE_38400);
    // fuGPS.sendCommand(FUGPS_PMTK_SET_NMEA_UPDATERATE_1HZ);
    fuGPS.sendCommand(FUGPS_PMTK_API_SET_NMEA_OUTPUT_RMCGGA);
}

void loop()
{
    // Valid NMEA message
    if (fuGPS.read())
    {
        // We don't know, which message was came first (GGA or RMC).
        // Thats why some fields may be empty.

        gpsAlive = true;

        Serial.print("Quality: ");
        Serial.println(fuGPS.Quality);

        Serial.print("Satellites: ");
        Serial.println(fuGPS.Satellites);
        
        Serial.print("Date: ");
        Serial.println(fuGPS.Days);
        
        Serial.print("Month: ");
        Serial.println(fuGPS.Months);

        Serial.print("Year: ");
        Serial.println(fuGPS.Years);

        if (fuGPS.hasFix() == true)
        {
            // Data from GGA message
            Serial.print("Accuracy (HDOP): ");
            Serial.println(fuGPS.Accuracy);

            Serial.print("Altitude (above sea level): ");
            Serial.println(fuGPS.Altitude);


            // Data from GGA or RMC
            Serial.print("Location (decimal degrees): ");
            Serial.println("https://www.google.com/maps/search/?api=1&query=" + String(fuGPS.Latitude, 6) + "," + String(fuGPS.Longitude, 6));
        }
    }

    // Default is 10 seconds
    if (fuGPS.isAlive() == false)
    {
        if (gpsAlive == true)
        {
            gpsAlive = false;
            Serial.println("GPS module not responding with valid data.");
            Serial.println("Check wiring or restart.");
        }
    }
}
```
 here is the code i am running and i dont receive date, everything(not including speed)  but date

**Comment by MeY0u** [comment]
found the problem in the FuGPS library, the value of tokensCount should be compared to 14 and not 13

**Comment by fu-hsi** [comment]
@MeY0u there is no problem with the library. RMC message has 13 tokens including message id:

https://aprs.gids.nl/nmea/#rmc

```
eg1. $GPRMC,081836,A,3751.65,S,14507.36,E,000.0,360.0,130998,011.3,E*62
eg2. $GPRMC,225446,A,4916.45,N,12311.12,W,000.5,054.7,191194,020.3,E*68
eg3. $GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W*70
              1    2    3    4    5     6    7    8      9     10  11 12
```

Perhaps your GPS module sending data out of standard. That's why it's better to display all incoming messages to analyze.

**Comment by MeY0u** [comment]
i use ATGM332D-5NR32 and i print the currentbuffer variable from the library and i didnt notice any difference between the standard and what i sends back.
all the tokens are at the correct index as you set it.

By the way, the library is pretty easy to modify, thats great bonus thank you.
